# Site config options
title: Dan Truong
email: dtruongservices@gmail.com
tagline: >-
    None of us are as smart as all of us combined!
description: >- 
    IT guy by day. Web hobbyist and data wrangler by night. 
baseurl: "" 
url: "" 
github_username:  dantruong
linkedin_username:  dantruong52435

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

