# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dan Truong
email: dtruongservices@gmail.com
tagline: >-
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lacinia augue arcu, pharetra interdum nisl maximus at. Maecenas vitae maximus libero. Duis auctor imperdiet lacus, sed porttitor felis commodo sit amet. Sed euismod leo eget dictum vestibulum. Aenean id neque leo.
description: >- 
    Pellentesque egestas, lectus vestibulum ornare condimentum, tellus dolor feugiat justo, pulvinar pretium risus purus a lectus. Sed et laoreet risus. Etiam fermentum in massa a malesuada. Integer a iaculis risus. Cras et magna pharetra, consectetur lorem ut, faucibus est. Vivamus mi orci, pretium sit amet pellentesque vitae, ultricies at tellus. Fusce massa sapien, pharetra nec massa eget, congue mattis tellus. Nullam metus dolor, congue vitae dapibus id, aliquet quis odio. Etiam at enim commodo, tempus lacus vitae, pulvinar diam. Praesent posuere nisi vitae dictum placerat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  dantruong
linkedin_username:  dantruong52435

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
